***1.Vectors,Matrices and Arrays***

In [2]:
#1.1 Creating a Vector
import numpy as np
vector_row=np.array([1,2,3])
vector_col=np.array([[1],[2],[3]])

In [3]:
#1.2 Creating a Matrix


matrix=np.array([[1,2],[3,4],[5,6]])
print(matrix)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
#not recommended
matrix_obj=np.asmatrix([[1,2],[1,2],[1,2]])
print(matrix_obj)

[[1 2]
 [1 2]
 [1 2]]


In [5]:
#1.3 Creating a Sparse Matrix(non-zero element)
from scipy import sparse
matrix=np.array([[0,0],[0,1],[3,0]])
#Create a compressed sparse row matrix
matrix_sparse=sparse.csr_matrix(matrix)
print(matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [6]:
#1.4 Selecting Elements
vectors=np.array([1,2,3,4,5,6])
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
vectors[2]

np.int64(3)

In [7]:
#first element is zero, not 1
matrix[1,1]


np.int64(5)

In [8]:
#Select all elements of a vector
vectors[:]

array([1, 2, 3, 4, 5, 6])

In [9]:
vectors[:3]

array([1, 2, 3])

In [10]:
vectors[:1]

array([1])

In [11]:
vectors[3:]

array([4, 5, 6])

In [12]:
vectors[-1]

np.int64(6)

In [13]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [15]:
#1.5 Describing a Matrix
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [16]:
#[Rows,Columns]
matrix.shape

(3, 4)

In [17]:
matrix.size


12

In [18]:
matrix.ndim

2

In [19]:
#1.6 Applying Operations to Elements
add_100=lambda i:i+100
vectorized_add_100=np.vectorize(add_100)
vectorized_add_100(matrix)

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

***Numpy arrays allows us to perform operations between arrays even if their dimensions are not the same(a process called BROADCASTING)***

In [20]:
matrix+100

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

In [21]:
#1.7 Finding the maximum and minimum values
np.max(matrix)

np.int64(12)

In [22]:
np.min(matrix)

np.int64(1)

In [23]:
np.max(matrix,axis=1)

array([ 4,  8, 12])

In [24]:
#1.8 Calculating the average,variance and sd
np.mean(matrix)

np.float64(6.5)

In [25]:
np.var(matrix)

np.float64(11.916666666666666)

In [26]:
np.std(matrix)

np.float64(3.452052529534663)

In [27]:
np.mean(matrix,axis=0)

array([5., 6., 7., 8.])

In [28]:
#1.9 Reshaping Arrays
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [29]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [30]:
matrix.size

12

In [31]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [32]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
# Transposing a vector or matrix
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [34]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
#Transpose
np.array([1,2,3,4]).T

array([1, 2, 3, 4])

In [36]:

np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [37]:
#1.11 Flatening a Matrix
# matrix into 1D    
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#Flatten is a simple method to transform a matrix into a 1D array 
matrix.reshape(1,-1)


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [39]:
#1.12 Finding the Rank of a matrix
np.linalg.matrix_rank(matrix)


np.int64(2)

In [40]:
#1.13 Calculating the Determinant
np.linalg.det(matrix)

np.float64(0.0)

In [41]:
#1.14 Getting the diagonal of a matrix
matrix.diagonal()

array([1, 5, 9])

In [42]:
matrix.diagonal(offset=1)

array([2, 6])

In [43]:
matrix.diagonal(offset=-1)

array([4, 8])

In [44]:
#1.15 Calculating the trace of a matrix
#sum of diagonal elements
matrix.trace()

np.int64(15)

In [45]:
sum(matrix.diagonal())

np.int64(15)

In [46]:
#1.16 Finding Eigenvalues and Eigenvectors
#A*v=lambda*v
matrix=np.array([[1,-1,3],[1,1,6],[3,8,9]])

In [47]:
eigenvalue,eigenvector=np.linalg.eig(matrix)

In [48]:
eigenvalue

array([13.55075847,  0.74003145, -3.29078992])

In [49]:
eigenvector

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

In [ ]:
#1.17 calculating the dot products
vec_a=np.array([1,2,3])
vec_b=np.array([4,5,6])
np.dot(vec_a,vec_b)

np.int64(32)

In [ ]:
# Python 3.5 above
vec_a @ vec_b

np.int64(32)

In [52]:
#1.18 Adding and Subtracting Matrices
matrix_a=np.array([[1,1,1],[1,1,1],[1,1,2]])
matrix_b=np.array([[1,3,1],[1,3,1],[1,3,8]])
np.add(matrix_a,matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [53]:
np.subtract(matrix_a,matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [ ]:
#Alternate
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [56]:
#1.1 Multiplying Matrices
mat_a=np.array([[1,1],[1,2]])
mat_b=np.array([[1,3],[1,2]])
np.dot(mat_a,mat_b)

array([[2, 5],
       [3, 7]])

In [57]:
mat_a @ mat_b

array([[2, 5],
       [3, 7]])

In [58]:
mat_a * mat_b

array([[1, 3],
       [1, 4]])

In [60]:
# 1.20 Inverting a matrix 
# AA^-1=I
matrix=np.array([[1,4],[2,5]])
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [61]:
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [62]:
# 1.21 Generating Random Values
np.random.seed(0)

In [63]:
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [ ]:
#Draw three numbers from a normal distribution with mean 0.0 and sd 1.0
np.random.normal(0.0,1.0,3)

array([-2.2683282 ,  1.33354538, -0.84272405])

In [ ]:
#Draw three numbers from a logistic distribution with mean 0.0 and scale 1.0
np.random.logistic(0.0,1.0,3)

array([ 2.10898075,  3.2778983 , -0.47496606])

In [ ]:
# Draw three numbers from a unifrom distribution over the interval [1.0,2.0)
np.random.uniform(1.0,2.0,3)

array([1.79172504, 1.52889492, 1.56804456])