***6.Handling Text***

In [1]:
#6.1 Cleaning Text 

text_data=[" Interrobang. by Aishwarya Henritte","Parking And Going. by Karl Gautier","Today Is The night. By Jarek Prakash"]
strip_whitespace=[s.strip() for s in text_data]
strip_whitespace


['Interrobang. by Aishwarya Henritte',
 'Parking And Going. by Karl Gautier',
 'Today Is The night. By Jarek Prakash']

In [2]:
#Remove periods
remove_periods=[s.replace(".","") for s in strip_whitespace]
remove_periods

['Interrobang by Aishwarya Henritte',
 'Parking And Going by Karl Gautier',
 'Today Is The night By Jarek Prakash']

In [3]:
def capitalizer(string:str)-> str:
    return string.upper()
capitalized=[capitalizer(s) for s in remove_periods]

In [4]:
capitalized

['INTERROBANG BY AISHWARYA HENRITTE',
 'PARKING AND GOING BY KARL GAUTIER',
 'TODAY IS THE NIGHT BY JAREK PRAKASH']

In [5]:
import re
def replace_letters_with_X(string:str)-> str:
    return re.sub("[a-zA-Z]","X",string)
replaced=[replace_letters_with_X(s) for s in capitalized]
replaced

['XXXXXXXXXXX XX XXXXXXXXX XXXXXXXX',
 'XXXXXXX XXX XXXXX XX XXXX XXXXXXX',
 'XXXXX XX XXX XXXXX XX XXXXX XXXXXXX']

In [6]:
#6.2 Parsing and Cleaning HTML
from bs4 import BeautifulSoup
html="""<div class='full_name'><span style='font-weight:bold'>Cyberpunk</span> Edgerunner</div>"""
soup=BeautifulSoup(html,"lxml")
soup.find("div",{"class":"full_name"}).text

'Cyberpunk Edgerunner'

In [7]:
#6.3 Removing Punctuation
import unicodedata
import sys
text_data=['hi!!! I. Love. This. Song.....','10000% Agree!!!! #LoveIT','Right?!!!!']
punctuation=dict.fromkeys(i for i in range(sys.maxunicode) if unicodedata.category(chr(i)).startswith('P')) 
[string.translate(punctuation) for string in text_data]

['hi I Love This Song', '10000 Agree LoveIT', 'Right']

In [9]:
%pip install nltk
import nltk
nltk.download('punkt')

  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Using cached nltk-3.9.1-py3-none-any.whl (1.5 MB)
Note: you may need to restart the kernel to use updated packages.


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [10]:
from nltk.tokenize import word_tokenize
string = "The science of today is the technology of tomorrow"
word_tokenize(string)

LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\ASUS/nltk_data'
    - 'd:\\180 days of ML\\.venv\\nltk_data'
    - 'd:\\180 days of ML\\.venv\\share\\nltk_data'
    - 'd:\\180 days of ML\\.venv\\lib\\nltk_data'
    - 'C:\\Users\\ASUS\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


In [15]:
#6.5 Removing Stop Words
from nltk.corpus import stopwords
import nltk
nltk.download('stopword')
tokenize_word=['i', 'love', 'this', 'song'  
            ,'10000', 'agree', 'loveit', 'right']
stopwords=set(stopwords.words('english'))
[word for word in tokenize_word if word not in stopwords]

[nltk_data] Error loading stopword: Package 'stopword' not found in
[nltk_data]     index


LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - 'C:\\Users\\ASUS/nltk_data'
    - 'd:\\180 days of ML\\.venv\\nltk_data'
    - 'd:\\180 days of ML\\.venv\\share\\nltk_data'
    - 'd:\\180 days of ML\\.venv\\lib\\nltk_data'
    - 'C:\\Users\\ASUS\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


In [13]:
#6.6 Stemming Words
from nltk.stem import PorterStemmer
tokenize_word=['running', 'ran', 'runs', 'easily', 'fairly']
ps=PorterStemmer()
[ps.stem(word) for word in tokenize_word]

['run', 'ran', 'run', 'easili', 'fairli']

In [14]:
#6.7 Tagging Parts of Speech
from nltk import pos_tag
from nltk.tokenize import word_tokenize
text_data="The science of today is the technology of tomorrow"
text_tagged=pos_tag(word_tokenize(text_data))
text_tagged


LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\ASUS/nltk_data'
    - 'd:\\180 days of ML\\.venv\\nltk_data'
    - 'd:\\180 days of ML\\.venv\\share\\nltk_data'
    - 'd:\\180 days of ML\\.venv\\lib\\nltk_data'
    - 'C:\\Users\\ASUS\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


In [16]:
'''TAG 
NNP-proper noun,singular,
NN-Noun,singular or mass,
RB-Adverb,
VBD-Verb,past tense,
VBG-Verb,gerund or present participle,
JJ-Adjective,
PRP-Personal pronoun'''

'TAG \nNNP-proper noun,singular,\nNN-Noun,singular or mass,\nRB-Adverb,\nVBD-Verb,past tense,\nVBG-Verb,gerund or present participle,\nJJ-Adjective,\nPRP-Personal pronoun'

In [17]:
#6.8 Encoding Text as a Bag of Words
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
text_data=np.array(["I love this song","I love it","I really love this song"])
count=CountVectorizer()
bag_of_words=count.fit_transform(text_data)
bag_of_words

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9 stored elements and shape (3, 5)>

In [18]:
bag_of_words.toarray()

array([[0, 1, 0, 1, 1],
       [1, 1, 0, 0, 0],
       [0, 1, 1, 1, 1]])

In [21]:
count.get_feature_names_out()

array(['it', 'love', 'really', 'song', 'this'], dtype=object)

In [23]:
count_2gram=CountVectorizer(ngram_range=(2,2),stop_words='english',vocabulary=['brazil'])
bag=count_2gram.fit_transform(text_data)
bag.toarray()

array([[0],
       [0],
       [0]])

In [24]:
count_2gram.vocabulary_

{'brazil': 0}

In [25]:
#6.9 Weighting Word Importance 
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
text_data=np.array(["I love this song","I love it","I really love this song"])
tfidf=TfidfVectorizer()
feature_matrix=tfidf.fit_transform(text_data)
feature_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9 stored elements and shape (3, 5)>

In [26]:
feature_matrix.toarray()

array([[0.        , 0.48133417, 0.        , 0.61980538, 0.61980538],
       [0.861037  , 0.50854232, 0.        , 0.        , 0.        ],
       [0.        , 0.37311881, 0.63174505, 0.4804584 , 0.4804584 ]])

In [ ]:
#frequency inverse document frequency
#tf-idf(t,d)=tf(t,d)*idf(t) t is a word, d is a document
#idf(t)=log_e(total number of documents/number of documents with term t in it)
tfidf.vocabulary_


{'love': 1, 'this': 4, 'song': 3, 'it': 0, 'really': 2}