***12.Model Selection***

In [22]:
import warnings
warnings.filterwarnings('ignore')

In [23]:
#12.1 Selecting Best Model Using Exhaustive Search
import numpy as np
from sklearn import linear_model,datasets
from sklearn.model_selection import GridSearchCV #it is a brute force approach to model selection using cross-validation.
iris=datasets.load_iris()
features=iris.data
target=iris.target
logreg=linear_model.LogisticRegression(max_iter=1000)
penalty=['l1','l2']
C=np.logspace(0,4,10)
hyperparameters=dict(C=C,penalty=penalty)
gridsearch=GridSearchCV(logreg,hyperparameters,cv=5,verbose=0)
best_model=gridsearch.fit(features,target)

In [24]:
np.logspace(0,4,10)

array([1.00000000e+00, 2.78255940e+00, 7.74263683e+00, 2.15443469e+01,
       5.99484250e+01, 1.66810054e+02, 4.64158883e+02, 1.29154967e+03,
       3.59381366e+03, 1.00000000e+04])

In [25]:
print('Best Penalty:',best_model.best_estimator_.get_params()['penalty'])
print('Best C:',best_model.best_estimator_.get_params()['C'])

Best Penalty: l2
Best C: 21.544346900318832


In [26]:
best_model.predict(features)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
#12.2 Selecting Best Model Using Randomized Search
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform
from sklearn import linear_model,datasets
iris=datasets.load_iris()
features=iris.data
target=iris.target
logreg=linear_model.LogisticRegression(max_iter=1000)
penalty=['l1','l2'] 
C=uniform(loc=0,scale=4)
hyperparameters=dict(C=C,penalty=penalty)
randomizedsearch=RandomizedSearchCV(logreg,hyperparameters,random_state=1,n_iter=100,cv=5,verbose=0)
best_model=randomizedsearch.fit(features,target)

In [28]:
uniform(loc=0,scale=4).rvs(10)

array([2.19525402, 2.86075747, 2.4110535 , 2.17953273, 1.6946192 ,
       2.58357645, 1.75034885, 3.567092  , 3.85465104, 1.53376608])

In [29]:
print('Best Penalty:',best_model.best_estimator_.get_params()['penalty'])
print('Best C:',best_model.best_estimator_.get_params()['C'])

Best Penalty: l2
Best C: 3.730229437354635


In [30]:
best_model.predict(features)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [31]:
#12.3 Selecting Best Model from multiple learning algorithms
import numpy as np
from sklearn import linear_model,datasets
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
np.random.seed(0)
iris=datasets.load_iris()
features=iris.data
target=iris.target
pipe=Pipeline([('classifier',LogisticRegression())])
search_space=[{'classifier':[LogisticRegression(max_iter=1000)],
               'classifier__penalty':['l1','l2'],
               'classifier__C':np.logspace(0,4,10)},
              {'classifier':[RandomForestClassifier()],
               'classifier__n_estimators':[10,50,100],
               'classifier__max_features':['auto','sqrt','log2']}]
gridsearch=GridSearchCV(pipe,search_space,cv=5,verbose=0)
best_model=gridsearch.fit(features,target)

In [32]:
best_model.best_estimator_.get_params()['classifier']
LogisticRegression(C=7.742636826811269, class_weight=None, dual=False,multi_class='ovr',n_jobs=1,random_state=None,solver='liblinear',tol=0.0001,verbose=0, penalty='l1',warm_start=False, max_iter=1000)

LogisticRegression(C=7.742636826811269, max_iter=1000, multi_class='ovr',
                   n_jobs=1, penalty='l1', solver='liblinear')

In [33]:
best_model.predict(features)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [34]:
#12.4 Selecting Best Models when preprocessing 
import numpy as np
from sklearn import datasets
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


np.random.seed(0)

iris=datasets.load_iris()
features=iris.data
target=iris.target
preprocess=FeatureUnion([("std",StandardScaler()),("pca",PCA())])
pipe=Pipeline([('preprocess',preprocess),('classifier',LogisticRegression())])
search_space=[{'preprocess__pca__n_components':[1,2,3],
               'classifier__penalty':['l1','l2'],
               'classifier__C':np.logspace(0,4,10)}]
clf=GridSearchCV(pipe,search_space,cv=5,verbose=0)
best_model=clf.fit(features,target)

In [35]:
clf.best_estimator_.get_params()['preprocess__pca__n_components'] #__pca__n_components : [1,2,3] in the search space to indicate that we wanted to discover if one,two or three principal components were best for our model.

2

In [36]:
#12.5 Speeding UP model Selection with Parallelization
import numpy as np
from sklearn import datasets,linear_model
from sklearn.model_selection import GridSearchCV
iris=datasets.load_iris()
features=iris.data

target=iris.target
logreg=linear_model.LogisticRegression()

penalty=['l1','l2']
C=np.logspace(0,4,10)
hyperparameters=dict(C=C,penalty=penalty)
gridsearch=GridSearchCV(logreg,hyperparameters,cv=5,verbose=0,n_jobs=-1) #n_jobs=-1 will use all the cores of your CPU to perform the search.
best_model=gridsearch.fit(features,target)


In [37]:
clf=GridSearchCV(pipe,search_space,cv=5,verbose=0,n_jobs=1) #n_jobs=-1 will use all the cores of your CPU to perform the search.
best_model=clf.fit(features,target)

In [38]:
#12.6 Speeding Up model Slection Using ALgorithm-specific parameters
from sklearn import linear_model, datasets
#scikit-learn's LogisticRegressionCV method includes a parameter Cs. If supplied a list,Cs is the candidate hyperparameter values to select from. Range 0.0001 and 10000. Downside only serach a range of values for C

iris=datasets.load_iris()
features=iris.data
target=iris.target
logit=linear_model.LogisticRegressionCV(Cs=100)
logit.fit(features,target)
linear_model.LogisticRegressionCV(Cs=100, class_weight=None, cv=None, dual=False,fit_intercept=True, intercept_scaling=1, max_iter=100, multi_class='ovr',n_jobs=None, penalty='l2', random_state=None,refit=True, scoring=None, solver='lbfgs', tol=0.0001, verbose=1)

LogisticRegressionCV(Cs=100, intercept_scaling=1, multi_class='ovr', verbose=1)

In [39]:
#12.7 Evaluating Performance after model selection 
import numpy as np
from sklearn import linear_model,datasets
from sklearn.model_selection import GridSearchCV,cross_val_score
iris=datasets.load_iris()
features=iris.data
target=iris.target
logistic=linear_model.LogisticRegression(max_iter=1000)
C=np.logspace(0,4,20)
hyperparameters=dict(C=C)
gridsearch=GridSearchCV(logistic,hyperparameters,cv=5,verbose=1,n_jobs=-1)
cross_val_score(gridsearch,features,target,).mean()

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits


np.float64(0.9666666666666668)

In [40]:
best_model=gridsearch.fit(features,target)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


In [41]:
scores=cross_val_score(gridsearch,features,target)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
